"""Constants."""

DOMAIN = "aquarite"
BRAND = "Hayward"
MODEL = "Aquarite"
PATH_HASCD = "main.hasCD"
PATH_HASCL = "main.hasCL"
PATH_HASPH = "main.hasPH"
PATH_HASRX = "main.hasRX"
PATH_HASUV = "main.hasUV"
PATH_HASHIDRO = "main.hasHidro"
PATH_HASBACKWASH = "main.hasBackwash"
